### PR TITLE
Android: convert Android.mk to Android.bp

### PR DESCRIPTION
**Pull request by LongPingWEI**

### CODE REVIEW

**Comment by LongPingWEI** [comment]
@relan  Could you merge v1.2.7 to android branch?

**Comment by LongPingWEI** [comment]
[Uploading aosp_exfat_build.log…]()
@relan There are dozens of warnings when compile exfat with aosp build system so I have add the "-Wno-error" flag to cflags.

**Comment by relan** [comment]
Thanks for your pull request!

Since which Android version is Soong supported?

Does `host_supported: true` mean that a binary will be compiled for host system too? If so, why is this needed?

> Could you merge v1.2.7 to android branch?

Just branch from `develop` and we can drop `android` branch.

> There are dozens of warnings when compile exfat with aosp build system so I add the "-Wno-error" flag to cflags.

OK. I should fix them one day...

**Comment by LongPingWEI** [comment]
@relan 
>Since which Android version is Soong supported?
More and more modules in aosp have converted their Android.mk to Android.bp.
>Does host_supported: true mean that a binary will be compiled for host system too? 
Yes
>If so, why is this needed?
In leeminghao's Android.mk, exfat also will be compiled for host system. And I just made a direct conversion. 
>Just branch from develop and we can drop android branch.
Since I have found that version 1.2.7 is newest version on master branch.

**Comment by relan** [comment]
> In leeminghao's Android.mk, exfat also will be compiled for host system. And I just made a direct conversion.

I don't think we need fuse-exfat or exfat-utils on host. Please set host_supported to false.

> Since I have found that version 1.2.7 is newest version on master branch.

`master` is always equal or behind `develop`. All other branches are experimental and I use to force-push to them. Please rebase on top of `develop`.

**Pull request closed without merging**
