### PR TITLE
Escape commas and backslashes in source path

### PR DESCRIPTION
**Pull request by chenxiaolong**
This fixes mounting issues in Android 6.0 where the source path is in
the form `/dev/block/vold/public:RDEV_MAJOR,RDEV_MINOR`, where
RDEV_MAJOR and RDEV_MINOR are their respective values.

### CODE REVIEW

**Comment by chenxiaolong** [comment]
The escaping is understood by `libfuse` as of https://github.com/libfuse/libfuse/commit/555d6b504308eac6b976321ce938ee4bec62c354 (from 2010)

**Comment by relan** [comment]
Thanks for contributing! I've implemented it in a more local way in a7282fe. Please review and if it's OK for you I'll merge it into `develop` branch.

**Comment by chenxiaolong** [comment]
Thanks @relan! a7282fe242341c262a631df86f02dbdd43bc4c0b seems fine to me. I've tested and verified that it's working in Android.

**Comment by relan** [comment]
Merged into `develop`. Let me know if there something else that can help you porting fuse-exfat to Android.

**Pull request closed without merging**
