### PR TITLE
Android: convert Android.mk to Android.bp

### PR DESCRIPTION
**Pull request by LongPingWEI**
In this pull request:
1. The `host_supported` option has been removed;
2. `android/config.h` has been updated to `1.2.7`;
3. The `Android.mk` file has been converted to `Android.bp`;

### CODE REVIEW

**Comment by relan** [comment]
Thanks for an update!

Did you try to integrate fuse-exfat into an actual Android ROM? Anything else needs to be done to achieve this?

**Comment by LongPingWEI** [comment]
## How to build `exfat-utils` for Android:
1. Clone this repository into `aosp` source tree;
2. Execute `source build/envsetup.sh` in $ANDROID_TOP;
3. Execute `lunch aosp_arm64`;
4. Enter exfat's directory and execute `mma -j`;
5. `mkexfat` `exfatfsck` `dumpexfat` `exfatlabel` will be found in `$ANDROID_TOP/out/target/generic_arm64/system/bin`;

## How to use exfat-utils:
1. Use `adb push` to replace exfat-utils in Android device;
2. For devices not support exfat originally, kernel support and vold modification is need.

**Comment by relan** [comment]
Merged into the feature branch, will include into a big update. Thanks for your contribution!

**Comment by pablomh** [comment]
Hi @relan, any ETA for that big update/merge? I'm thinking about including this into an AOSP derivative I contribute to and it'd make it easier to follow "develop" (HEAD) instead of branching and cherry-picking.

**Comment by relan** [comment]
I don't have a roadmap.

In fact, I can make a series of minor versions (1.3, 1.4, etc.) instead of a major one (2.0). Are there any other changes you'd like to see merged ASAP?

**Comment by pablomh** [comment]
That would be lovely and I sorry if it sounded as hurrying you to do it ASAP :)

**Pull request merged**
